import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://app-v2-rc1-aw.smarter.codes/signin');
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Microsoft Logo Sign In with' }).click();
  const page1 = await page1Promise;
  await page.goto('https://app-v2-rc1-aw.smarter.codes/');
  await page.getByRole('tab', { name: 'Services' }).click();
  await expect(page.getByRole('heading', { name: 'Services', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Open AgileMapping' })).toBeVisible();
  await page.getByRole('tab', { name: 'Clients' }).click();
  await expect(page.getByRole('columnheader', { name: 'Client Name' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Add Client [Alt+A]' })).toBeVisible();
  await page.getByRole('tab', { name: 'Projects' }).click();
  await expect(page.getByRole('heading', { name: 'Regulatory Project Management' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Add Project [Alt+P]' })).toBeVisible();
  await page.getByRole('tab', { name: 'Services' }).click();
  await page.getByRole('button', { name: 'Open Redaction' }).click();
  await page.getByRole('link', { name: 'Go to home' }).click();
  await page.getByRole('button', { name: 'Open Publishing' }).click();
  await expect(page.getByRole('heading', { name: 'Document Publishing' })).toBeVisible();
  await page.getByRole('link', { name: 'Go to home' }).click();
  await page.getByRole('button', { name: 'Open Request For Proposal' }).click();
  await expect(page.getByRole('heading', { name: 'Request For Proposal' })).toBeVisible();
  await page.getByRole('link', { name: 'Go to home' }).click();
  await page.getByRole('button', { name: 'Open Redaction' }).click();
  await expect(page.getByRole('heading', { name: 'Redact Document' })).toBeVisible();
  await page.getByRole('link', { name: 'Go to home' }).click();
  await page.getByRole('button', { name: 'Open AgileMapping' }).click();
  await expect(page.getByRole('heading', { name: 'Train Document' })).toBeVisible();
  await page.getByRole('textbox', { name: 'Enter desired output filename' }).click();
  await page.getByRole('textbox', { name: 'Enter desired output filename' }).fill('Test');
  await page.getByRole('button', { name: 'Select destination template [' }).click();
  await page.getByRole('textbox', { name: 'Search files' }).click();
  await page.getByRole('textbox', { name: 'Search files' }).fill('QA');
  await page.getByRole('button', { name: 'Expand QA Testing' }).click();
  await page.getByRole('button', { name: 'Folder: QA Testing' }).click();
  await page.getByRole('textbox', { name: 'Search files' }).click();
  await page.getByRole('textbox', { name: 'Search files' }).fill('');
  await page.getByRole('button', { name: 'Next page' }).click();
  await page.getByRole('button', { name: 'Next page' }).click();
  await page.getByRole('button', { name: 'Expand QA Testing' }).click();
  await page.getByRole('checkbox', { name: 'Select ICF_SET0_TRIMMED.docx' }).check();
  await expect(page.getByText('file selected')).toBeVisible();
  await expect(page.getByText('<Sponsor Name>/Protocol: <Protocol Number>INFORMED CONSENT DOCUMENT AGREEMENT')).toBeVisible();
  await page.getByRole('button', { name: 'Full Preview' }).click();
  await expect(page.getByLabel('Full Preview').getByText('<Sponsor Name>/Protocol: <Protocol Number>INFORMED CONSENT DOCUMENT AGREEMENT')).toBeVisible();
  await page.getByRole('button', { name: 'Close modal' }).click();
  await page.getByRole('button', { name: 'Select source provider' }).click();
  await page.getByRole('option', { name: 'Veeva' }).click();
  await expect(page.getByRole('button', { name: 'Select source provider' })).toBeVisible();
  await page.getByRole('button', { name: 'Expand Templates' }).click();
  await page.getByRole('checkbox', { name: 'Select 2.6.4 Template_Test.' }).check();
  await expect(page.getByRole('tab', { name: 'Metadata' })).toBeVisible();
  await expect(page.getByText('Name2.6.4 Template_Test.docx')).toBeVisible();
  await expect(page.getByText('file selected')).toBeVisible();
  await page.getByRole('button', { name: 'Select source provider' }).click();
  await page.getByRole('option', { name: 'Veeva' }).click();
  await page.getByRole('button', { name: 'Select source provider' }).click();
  await page.getByRole('option', { name: 'Sharepoint default' }).click();
  await expect(page.getByRole('button', { name: 'Select source provider' })).toBeVisible();
  await page.getByRole('checkbox', { name: 'Select output.docx' }).check();
  await page.getByRole('tab', { name: 'Non-Clinical' }).click();
  await page.getByRole('button', { name: 'Expand M264' }).click();
  await page.getByRole('checkbox', { name: 'Select 2.6.4 Template_Test.' }).check();
  await page.getByRole('checkbox', { name: 'Select 2.6.4 Template_DD (1).' }).check();
  await expect(page.getByText('file selected')).toBeVisible();
  await page.getByRole('tab', { name: 'Clinical', exact: true }).click();
  await page.getByRole('button', { name: 'Next page' }).click();
  await page.getByRole('button', { name: 'Next page' }).click();
  await page.getByRole('checkbox', { name: 'Select ICF_SET0_TRIMMED.docx' }).check();
  await page.getByRole('button', { name: 'Select [ENTER]' }).click();
  await expect(page.getByRole('button', { name: 'ICF_SET0_TRIMMED.docx [Alt+2' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'ICF_SET0_TRIMMED.docx [Alt+2' })).toBeVisible();
  await page.getByRole('button', { name: 'Select source documents [Alt+' }).click();
  await page.getByRole('tab', { name: 'Non-Clinical' }).click();
  await page.getByRole('tab', { name: 'Clinical', exact: true }).click();
  await page.getByRole('button', { name: 'Select source provider' }).click();
  await page.getByRole('option', { name: 'Veeva' }).click();
  await expect(page.getByRole('button', { name: 'Select source provider' })).toBeVisible();
  await page.getByRole('button', { name: 'Expand Labeling' }).click();
  await page.getByRole('button', { name: 'Expand Core Labeling' }).click();
  await page.getByRole('checkbox', { name: 'Select Module2.6.' }).check();
  await expect(page.getByText('1 file selected')).toBeVisible();
  await page.getByRole('button', { name: 'Select source provider' }).click();
  await page.getByRole('option', { name: 'Sharepoint default' }).click();
  await expect(page.getByRole('button', { name: 'Select source provider' })).toBeVisible();
  await page.getByRole('button', { name: 'Next page' }).click();
  await page.getByRole('textbox', { name: 'Search files' }).click();
  await page.getByRole('textbox', { name: 'Search files' }).fill('QA');
  await page.getByRole('checkbox', { name: 'Select QA Testing' }).check();
  await page.getByRole('button', { name: 'Done [ENTER]' }).click();

  await page.getByRole('button', { name: 'Open menu' }).click();
  await expect(page.getByRole('heading', { name: 'Settings' })).toBeVisible();
  await page.getByRole('switch', { name: 'Dark mode' }).click();
  await expect(page.getByText('ON', { exact: true })).toBeVisible();
  await page.getByRole('switch', { name: 'High contrast' }).click();
  await expect(page.getByLabel('High contrast').getByText('ON', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Open admin console Open admin' }).click();
  await expect(page.getByRole('heading', { name: 'Organization Users' })).toBeVisible();
  await page.getByRole('button', { name: 'Branding' }).click();
  await page.getByRole('button', { name: 'Configuration' }).click();
  await page.getByRole('button', { name: 'Usage' }).click();
  await page.getByRole('button', { name: 'About' }).click();
  await page.getByRole('button', { name: 'Open activities' }).click();
  await expect(page.getByRole('heading', { name: 'Activities' })).toBeVisible();
  await page.getByText('Stay up to date with recent').click();
  await page.getByRole('button', { name: 'Close Activities drawer' }).click();
  await page.getByRole('link', { name: 'Go to home' }).click();
  await page.getByRole('button', { name: 'Open Redaction' }).click();
  await page.getByRole('button', { name: 'Select Source document [Alt+2]' }).click();
  await expect(page.getByRole('heading', { name: 'Select Source Document' })).toBeVisible();
  await page.getByRole('button', { name: 'Cancel [ESC]' }).click();
  await page.getByRole('link', { name: 'Go to home' }).click();
  await page.getByRole('button', { name: 'Open Publishing' }).click();
  await page.getByRole('button', { name: 'Select source document [Alt+2]' }).click();
  await page.getByRole('checkbox', { name: 'Select Agile Writer test' }).check();
  await page.getByRole('button', { name: 'Select [ENTER]' }).click();
  await expect(page.getByRole('button', { name: 'Agile Writer test' })).toBeVisible();
  await page.getByRole('textbox', { name: 'Enter the name of document' }).click();
  await expect(page.getByRole('button', { name: 'Format Document [Alt+G]' })).toBeVisible();
  await page.getByRole('link', { name: 'Go to home' }).click();
  await page.getByRole('button', { name: 'Open Publishing' }).click();
  await page.getByRole('link', { name: 'Go to home' }).click();
  await page.getByRole('button', { name: 'Open Request For Proposal' }).click();
  await expect(page.getByRole('heading', { name: 'Request For Proposal' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Generate [Alt+G]' })).toBeVisible();
  await page.getByRole('link', { name: 'Go to home' }).click();
  await page.getByRole('button', { name: 'Open Redaction' }).click();
  await expect(page.getByRole('button', { name: 'Start Redaction [Alt+G]' })).toBeVisible();
  await page.getByRole('link', { name: 'Go to home' }).click();
  await page.getByRole('button', { name: 'Open Publishing' }).click();
  await expect(page.getByRole('button', { name: 'Format Document [Alt+G]' })).toBeVisible();
  await page.getByRole('link', { name: 'Go to home' }).click();
  await page.getByRole('button', { name: 'ORG' }).click();
  await expect(page.getByRole('dialog', { name: 'Select Client' }).getByRole('banner')).toBeVisible();
  await page.getByRole('button', { name: 'Close Select Client' }).click();
});