import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://app-v2-rc1-aw.smarter.codes/signin');
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Microsoft Logo Sign In with' }).click();
  const page1 = await page1Promise;
  await page.goto('https://app-v2-rc1-aw.smarter.codes/');
  await page.getByRole('button', { name: 'Open AgileMapping' }).click();
  await page.getByRole('textbox', { name: 'Enter desired output filename' }).click();
  await page.getByRole('textbox', { name: 'Enter desired output filename' }).fill('');
  await page.getByRole('textbox', { name: 'Enter desired output filename' }).click();
  await page.getByRole('textbox', { name: 'Enter desired output filename' }).click();
  await page.getByRole('textbox', { name: 'Enter desired output filename' }).fill('\tCSR_Template_20FEB2026.docx');
  await page.getByRole('textbox', { name: 'Enter desired output filename' }).click();
  await page.getByRole('textbox', { name: 'Enter desired output filename' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter desired output filename' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter desired output filename' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter desired output filename' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter desired output filename' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter desired output filename' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter desired output filename' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter desired output filename' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter desired output filename' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter desired output filename' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter desired output filename' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter desired output filename' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter desired output filename' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter desired output filename' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter desired output filename' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter desired output filename' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter desired output filename' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter desired output filename' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter desired output filename' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter desired output filename' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter desired output filename' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter desired output filename' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter desired output filename' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter desired output filename' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter desired output filename' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter desired output filename' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter desired output filename' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Enter desired output filename' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Enter desired output filename' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter desired output filename' }).fill('CSR_Template_20FEB2026.docx');
  await page.getByRole('textbox', { name: 'Enter desired output filename' }).click();
  await page.getByRole('textbox', { name: 'Enter desired output filename' }).click();
  await page.getByRole('textbox', { name: 'Enter desired output filename' }).fill('CSR_Test');
  await page.getByRole('button', { name: 'Select destination template [' }).click();
  await page.getByRole('textbox', { name: 'Search files' }).click();
  await page.getByRole('textbox', { name: 'Search files' }).fill('\tCSR_Template_20FEB2026.docx');
  await page.getByRole('textbox', { name: 'Search files' }).click();
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).fill('CSR_Template_20FEB2026.docx');
  await page.getByRole('button', { name: 'Expand CSR' }).click();
  await page.getByRole('checkbox', { name: 'Select CSR_Template_20FEB2026' }).check();
  await page.getByRole('button', { name: 'Select [ENTER]' }).click();
  await page.getByRole('button', { name: 'Select source documents [Alt+' }).click();
  await page.getByRole('textbox', { name: 'Search files' }).click();
  await page.getByRole('textbox', { name: 'Search files' }).fill('MOCK');
  await page.getByRole('button', { name: 'Expand CSR' }).click();
  await page.getByRole('checkbox', { name: 'Select CSR' }).check();
  await expect(page.getByRole('button', { name: 'File: Mock_CSR_list.docx' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'File: Mock_CSR_Protocol.docx' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'File: Mock_CSR Key' })).toBeVisible();
  await page.getByRole('button', { name: 'Done [ENTER]' }).click();
  await page.getByRole('button', { name: 'Start Training [Alt+G]' }).click();
  await expect(page.getByRole('heading', { name: 'Loading Training Workspace' })).toBeVisible();
  await page.getByRole('button', { name: 'Show mapping controls' }).click();
  await page.getByRole('button', { name: 'Close Mapping Controls drawer' }).click();
  await page.getByRole('button', { name: 'Show document list' }).click();
  await expect(page.getByRole('button', { name: 'Show Mock_CSR_list.docx' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Show Mock_CSR Key' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Show Mock_CSR _Tables_30Oct25' })).toBeVisible();
  await page.getByRole('button', { name: 'Show mapping controls' }).click();
  await page.locator('#placeholder-0').click();
  await page.getByRole('button', { name: 'Close Mapping Controls drawer' }).click();
});