import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://app-v2-rc1-aw.smarter.codes/signin');
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Microsoft Logo Sign In with' }).click();
  const page1 = await page1Promise;
  await page1.getByRole('textbox', { name: 'someone@synterex.com' }).click();
  await page1.getByRole('textbox', { name: 'someone@synterex.com' }).fill('s.vignesh@smarter.codes');
  await page1.getByRole('button', { name: 'Next' }).click();

  await page1.getByRole('textbox', { name: 'Enter the password for s.' }).click();
  await page1.getByRole('textbox', { name: 'Enter the password for s.' }).fill('temp@0503');
  await page1.getByRole('button', { name: 'Sign in' }).click();
  await page1.getByRole('checkbox', { name: 'Don\'t show this again' }).check();
  await page1.getByRole('button', { name: 'Yes' }).click();
  await page.goto('https://app-v2-rc1-aw.smarter.codes/');
  await page.getByRole('button', { name: 'Open AgileMapping' }).click();
  await page.getByRole('button', { name: 'Select destination template [' }).click();
  await page.getByRole('textbox', { name: 'Search files' }).click();
  await page.getByRole('textbox', { name: 'Search files' }).fill('IDE');
  await page.getByRole('textbox', { name: 'Search files' }).click();
  await expect(page.getByRole('textbox', { name: 'Search files' })).toBeVisible();
  await page.getByRole('textbox', { name: 'Search files' }).click();
  await page.getByRole('textbox', { name: 'Search files' }).click();
  await page.getByRole('textbox', { name: 'Search files' }).click();
  await page.getByRole('textbox', { name: 'Search files' }).fill('IDE196-001_CSR_Destination%20Template_18May2026_Final.docx');
  await page.getByRole('textbox', { name: 'Search files' }).click();
  await page.getByRole('textbox', { name: 'Search files' }).click();
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).fill('IDE196-001_CSR_Destination Template_18May2026_Final.docx');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.locator('div').filter({ hasText: /^No files match "IDE196-001_CSR_Destination Template_18May2026_Final\.docx"\.$/ }).nth(1).click();
  await page.getByRole('textbox', { name: 'Search files' }).click();
  await expect(page.getByRole('textbox', { name: 'Search files' })).toBeVisible();
  await page.getByText('No files match "IDE196-').click();
  await page.getByRole('heading', { name: 'Select Destination Template' }).click();
  await expect(page.getByRole('heading', { name: 'Select Destination Template' })).toBeVisible();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('button', { name: 'Select source documents [Alt+' }).click();
  await page.getByRole('textbox', { name: 'Search files' }).click();
  await page.getByRole('textbox', { name: 'Search files' }).fill('IDE196%20Investigators%20Brochure_v13.pdf');
  await page.getByRole('textbox', { name: 'Search files' }).click();
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Search files' }).fill('IDE196%20Investigators Brochure_v13.pdf');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).fill('IDE19Investigators Brochure_v13.pdf');
  await page.getByRole('textbox', { name: 'Search files' }).press('ControlOrMeta+z');
  await page.getByRole('textbox', { name: 'Search files' }).fill('IDE196 Investigators Brochure_v13.pdf');
  await page.locator('div').filter({ hasText: /^No files match "IDE196 Investigators Brochure_v13\.pdf"\.$/ }).nth(1).click();
  await expect(page.getByRole('textbox', { name: 'Search files' })).toBeVisible();
  await page.getByText('Upload[Alt+U]Select All•').click();
  await page.getByRole('textbox', { name: 'Search files' }).click();
  await page.getByRole('textbox', { name: 'Search files' }).click();
  await page.getByRole('textbox', { name: 'Search files' }).fill('Efficacy%20Tables_Test_EP');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).fill('Efficacy Tables_Test_EP');
  await expect(page.getByRole('textbox', { name: 'Search files' })).toBeVisible();
  await page.getByRole('textbox', { name: 'Search files' }).click();
  await page.getByRole('textbox', { name: 'Search files' }).fill('Safety%20Tables_Test_EP');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).fill('Safety Tables_Test_EP');
  await expect(page.getByRole('textbox', { name: 'Search files' })).toBeVisible();
  await page.getByRole('textbox', { name: 'Search files' }).click();
  await page.getByRole('textbox', { name: 'Search files' }).fill('Test%20%5BFrom%20Synterex%5D');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Search files' }).fill('Test%20%5BFrom%20Synterex D');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).fill('Test%20%5BFrom%20Serex D');
  await page.getByRole('textbox', { name: 'Search files' }).press('ControlOrMeta+z');
  await page.getByRole('textbox', { name: 'Search files' }).fill('Test%20%5BFrom%20Synterex D');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).fill('Test%20%5BFromSynterex D');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Search files' }).fill('Test%20%5BFrom Synterex D');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Search files' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Search files' }).fill('Test BFrom Synterex D');
  await expect(page.getByRole('textbox', { name: 'Search files' })).toBeVisible();
  await expect(page.locator('div').filter({ hasText: /^No files match "Test BFrom Synterex D"\.$/ }).nth(1)).toBeVisible();
  await expect(page.getByText('No files match "Test BFrom')).toBeVisible();
  await page.getByRole('textbox', { name: 'Search files' }).click();
  await page.getByRole('textbox', { name: 'Search files' }).fill('');
  await page.getByRole('button', { name: 'Expand Protocol [Phase_1 BOIN]' }).click();
  await page.getByRole('button', { name: 'Expand Test', exact: true }).click();
  await page.getByRole('checkbox', { name: 'Select Test', exact: true }).check();
  await expect(page.getByRole('button', { name: 'Folder: Test', exact: true })).toBeVisible();
  await expect(page.getByText('files selected')).toBeVisible();
  await expect(page.getByRole('checkbox', { name: 'Select Test', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Folder: Test', exact: true })).toBeVisible();
  await page.getByRole('checkbox', { name: 'Select Test', exact: true }).uncheck();
  await expect(page.getByRole('checkbox', { name: 'Select Test', exact: true })).toBeVisible();
  await expect(page.getByText('No files selected')).toBeVisible();
  await page.getByRole('checkbox', { name: 'Select Protocol [Phase_1 BOIN]' }).check();
  await expect(page.getByText('files selected')).toBeVisible();
  await expect(page.getByRole('checkbox', { name: 'Select Protocol [Phase_1 BOIN]' })).toBeVisible();
  await page.getByRole('button', { name: 'Done [ENTER]' }).click();
  await page.getByRole('button', { name: 'Done [ENTER]' }).click();
});