import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  // Recording...await page.goto('https://app-v2-rc1-aw.smarter.codes/signin');
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Microsoft Logo Sign In with' }).click();
  const page1 = await page1Promise;
  await page.goto('https://app-v2-rc1-aw.smarter.codes/');
  await page.getByRole('button', { name: 'Open AgileMapping' }).click();
  await page.getByRole('button', { name: 'Select source documents [Alt+' }).click();
  await expect(page.getByRole('heading', { name: 'Select Source Documents' })).toBeVisible();
  await page.getByRole('tab', { name: 'Non-Clinical' }).click();
  await expect(page.getByRole('button', { name: 'Folder: Module264' })).toBeVisible();
  await page.getByRole('tab', { name: 'Clinical', exact: true }).click();
  await page.getByRole('button', { name: 'Sharepoint' }).click();
  await page.getByRole('button', { name: 'Veeva' }).click();
  await page.getByRole('button', { name: 'Expand Nonclinical' }).click();
  await page.getByRole('button', { name: 'Expand Clinical' }).click();
  await page.getByRole('button', { name: 'Expand Study Reports' }).click();
  await page.getByRole('button', { name: 'Expand Regulatory Support' }).click();
  await page.getByRole('checkbox', { name: 'Select Nonclinical' }).check();
  await expect(page.getByText('files selected')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Folder: Nonclinical' })).toBeVisible();
  await page.getByRole('button', { name: 'File: fake cyp 4.2.2.6.docx' }).click();
  await expect(page.getByRole('button', { name: 'Full Preview' })).toBeVisible();
  await page.getByRole('button', { name: 'Preview', exact: true }).click();
  await expect(page.locator('section').filter({ hasText: 'X12345: Cytochrome P450' })).toBeVisible();
  await page.getByRole('button', { name: 'Full Preview' }).click();
  await expect(page.getByLabel('Full Preview').locator('section').filter({ hasText: 'X12345: Cytochrome P450' })).toBeVisible();
  await page.getByRole('button', { name: 'Close modal' }).click();
  await page.getByRole('button', { name: 'Done [ENTER]' }).click();
  await expect(page.getByRole('button', { name: '6 files: a.docx, 4.2.2.2' })).toBeVisible();
  await page.getByRole('button', { name: '6 files: a.docx, 4.2.2.2' }).click();
  await page.getByRole('button', { name: 'Veeva' }).click();
  await page.getByRole('button', { name: 'Sharepoint default' }).click();
  await page.getByRole('button', { name: 'Expand Protocol [Phase_1 BOIN]' }).click();
  await page.getByRole('checkbox', { name: 'Select Protocol [Phase_1 BOIN]' }).check();
  await page.getByRole('checkbox', { name: 'Select Protocol', exact: true }).check();
  await page.getByRole('button', { name: 'Expand Protocol' }).click();
  await expect(page.getByRole('checkbox', { name: 'Select ABC-123_synopsis_modified_v3(with headings).url' })).toBeVisible();
  await expect(page.getByRole('checkbox', { name: 'Select ABC-123_synopsis_Modified.docx' })).toBeVisible();
  await expect(page.getByText('files selected')).toBeVisible();
  await page.getByRole('button', { name: 'Done [ENTER]' }).click();
  await expect(page.getByRole('button', { name: '7 files: ABC-' })).toBeVisible();
});